### ISSUE TITLE
Deprecated method used

### ISSUE THREAD

**Issue by est31** [kaadmy/pixture#14]
When I run the game, my console gets spammed by deprecation messages:

```
WARNING[Server]: Deprecated usage of get_node_group, use get_item_group instead
```

Perhaps use the current method?

**Comment by kaadmy** [comment]
Welp, I don't get that message... When was it deprecated?

**Comment by est31** [comment]
I'm not sure but it was before 0.4.10.

I get the message when I run it in current dev version of minetest, it introduced warningstream which is on by default. For you it probably logged to infostream or verbosestream.

**Comment by est31** [comment]
Thanks for fixing.
