### ISSUE TITLE
doesn't work on 0.4.13 release

### ISSUE THREAD

**Issue by asl97** [kaadmy/pixture#2]
maybe you should leave a note in the readme that say this doesn't work on the release
and maybe a link to the forum topic.

**Comment by kaadmy** [comment]
Why doesn't it work? I have been testing only with dev, and it works...

**Comment by asl97** [comment]
link to latest commit for the file: https://github.com/kaadmy/pixture/blob/81ed6e2c389733d98346b16bd29d5414c2ad5968/mods/default/model.lua#L72

`get_properties()` wasn't added till May 28, 2015 and 0.4.13 was release on August 20, 2015

commit: https://github.com/minetest/minetest/commit/c0335f7d13ee46c6a46d0ceebea96960439ec9fd

**Comment by kaadmy** [comment]
Ah, I actually didn't know that.

**Comment by asl97** [comment]
it at least started without errors.
edited to add related commit: https://github.com/kaadmy/pixture/commit/562fc9e1b810c9f4fae30d24d87bf9717c13a2c8
