### ISSUE TITLE
Boats (and vehicles in general)

### ISSUE THREAD

**Issue by jasonmacduffie** [kaadmy/pixture#22]
It would be really neat if pixture had boats! Are there plans for this?

Minecarts and riding animals would also be cool, but less important than boats.

**Comment by kaadmy** [comment]
I was originally going to add boats and other vehicles, but seeing how laggy Minetest_game's boats are, I dropped the idea.

**Comment by jasonmacduffie** [comment]
Ah, OK I see. I hope they become more useable in the future :(
