### ISSUE TITLE
Group letter “G” is hidden by item image in crafting guide

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#25]
In the crafting guide, the group letter “G” is obscured by the item image, but I think it is supposed to be drawn in *front* of the item image, right? Otherwise the player does not know this slot stands for a group.
Visible example: Recipe for net.

Tested in: f01a0051c63bddae45d1b0ae7289a153a10c5f69

EDIT: There is a related issue: The crafting result number is also partially or completely invisible. Take the fertilzer recipe for example. The number in the result slot is hard to read beause the fertilzer icon is drawn over it.

**Comment by kaadmy** [comment]
:/ I think the inventory order changed to a fixed order recently instead of the order stuff is in the inventory string, this wasn't a problem when I wrote that code.
