### ISSUE TITLE
Odd crafting recipe alternation arrows

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#26]
The behaviour of the crafting recipe alternatives arrows (up and down) is odd. Up means next alternative and down means previous.
But somehow I think the reverse order “feels” more natural to me. Do you agree?

Tested in: f01a0051c63bddae45d1b0ae7289a153a10c5f69

**Comment by kaadmy** [comment]
I can easily swap it, but up feels more like "increase" or "more" to me. This is more personal opinion though, so i'll close this.

**Comment by asl97** [comment]
@kaadmy how about making it loop around when it reach the end?
that way, ether direction would be fine.

**Comment by kaadmy** [comment]
Good idea, I'll try that.
