### ISSUE TITLE
Crafting guide shows itemstring instead of item description/name

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#27]
It looks odd that the crafting guide shows the itemstring instead of the “real” item name (`description` field). E.g. if you ask for the gravel recipe, you see “default:gravel” instead of “Gravel”. For an end-user application, showing internal data seems odd.

In the unlikely case this is intentional, may I suggest a compromise in showing both “real” name and the itemstring?

Tested in: f01a0051c63bddae45d1b0ae7289a153a10c5f69

**Comment by kaadmy** [comment]
I think the existing tooltip is sufficient? I think I originally did this because some mods have duplicate descriptions, and  this way it's easier to use /give.

**Comment by Wuzzy2** [comment]
I understand the use case but I don't think a crafting guide is the best place to expose the itemstring. Because the crafting guide does not list all items. I don't really have a better idea to expose an itemstring. :-/

Maybe this could be fixed in the engine, by writing the itemstring of the wielded item into the debug screen.

Since you probably want to keep this, I now only suggest to write “Itemstring: default:whatever”.
