### ISSUE TITLE
Remove boring achievements

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#28]
I suggest to remove the following boring or unfair achievements:

* Like clockwork
* Killathon
* First join

Reason: There is no skill involved and also do not relate to the gameplay at all. The Killathon achievement is an award for poor skills, so is paradoxical. xD Also, if you built your home base far from spawn, you certainly do not want to try to earn this award by killing yourselves 10 times.

**Comment by kaadmy** [comment]
Will do.
