### ISSUE TITLE
Suggestion: Disable minimap by default, require map item to use

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#29]
Minetest 0.4.14 included the minimap feature.
So why not changing the way how the map item works? At the start, the minimap feature could be disabled. The player has to carry the map item somewhere in the inventory to be allowed to use the minimap.

Implementation is fairly straightforward: In my `orienteering` mod I basically implemented the feature with the Automapper item. Feel free to use the code from this mod, if you wish.

**Comment by kaadmy** [comment]
Could I have a link to your mod? Unless I'm mistaken, there's no way to disable the builtin minimap via a mod.

**Comment by Wuzzy2** [comment]
You're wrong. You can use `player:hud_set_flags({minimap = false})`.
Here's the link to the mod:
https://forum.minetest.net/viewtopic.php?t=15247

Tip: Here is a search engine for mods _which actually works_:
http://krock-works.16mb.com/MTstuff/modSearch.php

This will make your Minetest life a lot easier. :-)

**Comment by kaadmy** [comment]
*Bump*
This seems more like a gimmick feature; I could probably just disable the radar entirely and it wouldn't change gameplay much at all, since a lot of people don't use the minimap at all.

**Comment by Wuzzy2** [comment]
@kaadmy: Note that Pixture has a map item. It is completely useless right now.

By the way: I disagree that people rarely use the minimap. Note that removing the map feature entirely severely nerfs the gameplay, especially if you like to travel long ways. But I can kinda see a rationale here because the minimap feature also includes the radar, which may make things too easy.

So I ask you: Is your decision to remove the map feature from Pixture final? If yes, then the map item clearly has no place in Pixture. For compability, you could alias the map to paper or something, so people won't get an unknown item in inventory after updating.

**Comment by kaadmy** [comment]
Well I'll just ignore compatibility for now since changing the crafting system will likely change balance a lot, as well as other changes (completely new tool dig times) that may affect gameplay a fairly large amount.
