### ISSUE TITLE
Rain looks awkward on floor

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#30]
When it rains, the rain drops look pretty awkward when they hit the floor. Those look like little blue spikes projecting out of the floor because the do not instantly or quickly disappear after impact.

Tested in: f01a005

**Comment by kaadmy** [comment]
Minetest's engine has no way of removing particles when they hit something, I can't do anything about this one.

**Comment by Wuzzy2** [comment]
Shoot! I will make an issue for Minetest then.

**Comment by Wuzzy2** [comment]
Oh. I just discovered that in May a PR was merged which adds the feature you need:

https://github.com/minetest/minetest/pull/3888

From the new `lua_api.txt`:

```
collision_removal = false,
-- ^ collision_removal: if true then particle is removed when it collides,
-- ^ requires collisiondetection = true to have any effect
```

**Comment by kaadmy** [comment]
Oh, that's nice.
