### ISSUE TITLE
Achievement ideas

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#32]
Hi! I have some ideas for new achievements:

- Musician: Craft a music player
- Trader: Craft a trading book
- Gold Rush: Dig 60 gold
- Master Carpenter: Craft 200 reinforced frames
- Master Stonemason: Craft 200 reinforced cobbles
- Enlightened: Place 9 lumien crystals
- Smelting Room: Craft 20 furnaces
- Builder: Craft 180 bricks
- Citizen: Find a village*
- Little Ranger: Tame an animal
- Parachuter: Craft 5 parachutes
- Librarian: Craft 10 bookshelves
- Sandman: Craft 60 compressed sandstone
- Hardened Miner: Craft 3 carbon steel pickaxes
- Cave Builder: Place 60 stone
- Fertile: Craft 100 fertilizers
- Welcome to the mountains: Collect dry grass
- Drain the swamp: Dig 30 swamp dirt

\* = If this can't be checked directly, it might need a different goal or a task which could only be done in villages (as “proof” the player found a village), like digging an unique block or whatever.

**Comment by kaadmy** [comment]
These are all pretty easy, I can add them, but unfortunately I can't test them as Minetest has gotten too slow for me to run at all since 0.4.14.

**Comment by kaadmy** [comment]
I'm adding these right now; are the numbers mostly random or do they have some meaning?
Example: `Craft 180 bricks` `Dig 30 swamp dirt`

**Comment by Wuzzy2** [comment]
The numbers were carefully chosen to be obtainable in a reasonable amount of time. Not too small (so you don't get them too quickly) but not too large (so they don't just too boring to obtain).

The idea behind all this achievements is encourage the player to explore the game a bit more (including the items deep in the crafting tree). :)
