### ISSUE TITLE
Flowing water will drop if blasted by TNT

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#34]
Flowing water can be collected if you use a TNT next to it. The flowing water will drop if it is affected by a TNT explosion, and you can collect the flowing water item.

Without having looked at the code, I wanna bet that you just have to write `drop = "",` to fix this bug. :P

**Comment by kaadmy** [comment]
Thanks for noticing, I didn't think of this when I wrote that :D
