### ISSUE TITLE
Player model is loaded again and again while chat is opened

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#40]
Here's a really strange bug:

In MT 0.4.15, when I open the chat with the chat key, the console gets spammed with this:

```Loaded mesh: character.b3d
Loaded mesh: character.b3d
Loaded mesh: character.b3d
Loaded mesh: character.b3d
Loaded mesh: character.b3d
```

And so on, until I close the chat thingie. Also, when I look at my player model, I see that the animation constantly resets to start.

Tested in dec846e26507f14c30a35d16cc2fa70f967d8417.

**Comment by kaadmy** [comment]
This is indeed a problem, but I haven't figure out what condition triggers it so it's harder to track down.
This will definitely need a fix as there's probably a simple solution.

**Edit:** if you can find a condition to reliably reproduce this, it'd be really useful.

**Comment by kaadmy** [comment]
It seems that if you spawn and don't move for a few seconds, this happens pretty reliably...

**Comment by kaadmy** [comment]
Hm, it seems to only happen if you haven't moved much and open the inventory... I can repro but I have no idea what triggers it.
