### ISSUE TITLE
Crafting guide oddly shows stairs for many recipes

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#41]
The crafting guide is confusing. It shows stairs for many recipes, like the basic tools or doors.

For example, the crafting guide shows 3 wooden stairs for pickaxes. This is very odd.

I can recall from one let's play that the player thought the recipes were wery _weird_ because you apparently need 3 wooden stairs to craft a pickaxe. The player didn't know that normal wood works as well (the crafting guide didn't show the normal recipe). Fun fact: You can *actually* use stairs to craft a pickaxe. Whether or not this is intentional is not my concern here.

I think the real problem is here that Pixture shows an inappropriate/misleading symbol for group slots.
This can be fixed by doing the following:

1. For each group, define a “stereotype” item which represents that group. For the group “planks” that would be Planks, for “stone” it would be Stone, etc.
1. Make group slots stand out from the rest, so the player sees those require a item from a group, and not a particular item. Using the letter “G” has proven to work well, but if you have a better idea, that's great, too.

Just look how the mod `craftguide` by jp / kilbith does this. In this mod, the stereotype is implemented by using a simple lookup table with a fallback option in case the group is unknown (important for modding).

**Comment by kaadmy** [comment]
Does the "G" character show up on groups for you? The code agrees that it should be there, and I remember formspec render sorting was changed at some point around 0.4.14-0.4.15...

**Comment by Wuzzy2** [comment]
Note that item image buttons allow to have their own label. I recommend to use that one. Unless you can think of a better / more obvious to display this (maybe different background color or whatever).

Did you maybe try to overlay a label over an item image button?

**Comment by kaadmy** [comment]
I have overrides for groups now, but they're currently only applied to group:wood and group:stone.
Suggestions for more would be appreciated if you find any.
