### ISSUE TITLE
Rightclicking bed while walking does not stop player movement

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#45]
How to reproduce:

* Place bed on a large open floor
* Walk
* While walking, rightclick the bed
* You will now continue to move into this direction forever, even if you don't walk
* Bonus: If you can't reach the bed anymore, you are crippled for life as you can't walk anymore. xD You have to get a new bed by cheating to enable walking again.

Tested in: dec846e26507f14c30a35d16cc2fa70f967d8417

**Comment by kaadmy** [comment]
This is a known problem, but Minetest doesn't allow access to set a player's velocity so the only good way to fix this is by force warping the player back to the bed every 10 seconds or so.

**Comment by kaadmy** [comment]
I just tested, this is also a bug in MTG...

**Comment by Wuzzy2** [comment]
The fact that MTG is broken, too, is irrelevant.

Looks like we need to request an engine fix first.

**Comment by kaadmy** [comment]
Well since player velocity is basically client-side, it'd probably be a mess to change this so server-side mods can modify a player's velocity.
Feel free to open an issue on the Minetest engine repository, but I don't think it'll happen any time soon.

**Comment by kaadmy** [comment]
Ah, thanks. Didn't know that existed...
Was it added after 0.4.13? I might not have seen it them.

**Comment by kaadmy** [comment]
I have a partial fix now, reconnecting will reset your position to the bed and since reconnecting zeroes velocity this works fairly well because you're not moving anymore.
