### ISSUE TITLE
Water buckets can destroy fences

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#46]
Fun bug:

* Place a fence post on the floor
* Take water bucket
* Place water on the node *below* the fence

Expected behaviour: Nothing
Actual behaviour: Water is placed where the fence is, destroying the fence in the process

Tested in: dec846e26507f14c30a35d16cc2fa70f967d8417

**Comment by kaadmy** [comment]
Can confirm this happens.

**Comment by Wuzzy2** [comment]
Thank you!
