### ISSUE TITLE
Remove “cheating” privileges from singleplayer

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#47]
I noticed that singleplayer has some privileges enabled by default which I think should be off by default:

* `weather`
* `uberspeed`
* `fixlight` (Is this `fixlight` command really needed? Would make more sense to have this in `builtin` of Minetest)

**Comment by kaadmy** [comment]
Is there a way to change the singleplayer privs? AFAIK all privs except some obvious ones (fly, give) are given to singleplayer.

**Comment by Wuzzy2** [comment]
Check your documentation on `minetest.register_privilege` again …

**Comment by kaadmy** [comment]
Fixed in d4103c3c1554bf48c5b0024d315bde66ffad2cfc
