### ISSUE TITLE
Crafting achievements do not work

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#50]
I noticed that all achievements which require you to craft something do not work at all.

04040b5e2eeabc7c73b44a422f84da6395db8a13

**Comment by kaadmy** [comment]
Oh right.. they still use the default `minetest.register_on_craft` callbacks, will fix ASAP

**Comment by kaadmy** [comment]
Fixed in 8161cc7caba35dbe8b4ab67dba373f9e55ca5d57

**Comment by Wuzzy2** [comment]
Not really fixed.
The achievement counter is not increased correctly.
E.g. if you craft 2 bricks at once, the counter is only increased by 1.
If you craft 20 bricks at once, the counter is still only increased by 1.
