### ISSUE TITLE
More achievement ideas

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#51]
Here are more ideas for achievements:

* Hunter: Kill 5 animals for food*
* Capitalist: Earn 60 gold by trading with villagers
* Ranger: Catch an animal
* Best Friends Forever: Tame an animal
* Bomb has been defused: Kill a mine turtle
* World Tour: Visit all biomes**

---
Footnotes:
\* = Only animals which drop food are counted
\*\* = Could replace the achievement “Welcome to the mountains”, becaue the idea for this one was mostly just exploration. Not sure how to implement this now, but I heard the next Minetest release will include functions to query the biome for any given pos

Thanks for your attention. :-)

**Comment by kaadmy** [comment]
I just checked the latest Lua API quickly, there don't seem to be any biome query functions.
I'd love to do biome-specific stuff but it isn't possible currently AFAIK.

**Comment by kaadmy** [comment]
I'll skip the "Capitalist" and "World Tour" achievements since the latter is hard, if not impossible, and the first is a bit pointless since NPCs can trade for almost anything so gold is used rarely.

**Comment by kaadmy** [comment]
I just had an idea :D

- Best Friends Forever: Tame an animal
- Worst Friends Forever: Capture an animal

**Comment by kaadmy** [comment]
All achievements except Capitalist and World Tour have been added in a66e8c7620b303d404a8c30fed3eb427d6251e3b
