### ISSUE TITLE
Some crafting recipes went missing?

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#52]
I am not sure, but I think Pixture may have lost some crafting recipes when introducing the new crafting system.
If I recall correctly, you were previously able to craft lumien crystals from lumien blocks. This is no longer possible.

I suspect there could be other crafting recipes which somehow went missing. Can you please check?

8161cc7caba35dbe8b4ab67dba373f9e55ca5d57

**Comment by kaadmy** [comment]
Yeah I haven't added a lot of them, I just did the ones in the default and bed mods :D
I _will_ add them, I just want to get the bugs out of the way first.

**Comment by Wuzzy2** [comment]
Good, thanks.
