### ISSUE TITLE
Chest formspec has crafting guide button

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#53]
8161cc7caba35dbe8b4ab67dba373f9e55ca5d57.

The chest formspec still has the crafting guide button (question mark). It does nothing.

**Comment by kaadmy** [comment]
I won't do anything about this since it's only old formspecs that have this issue and I won't worry about backwards compatibilty before 0.1.0.

**Comment by Wuzzy2** [comment]
Okay.
