### ISSUE TITLE
Item name “Wrought Iron Spear" appers twice in crafting guide

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#59]
If you check out the crafting guide, you'll see the name “Wrought Iron Spear” twice.
One appears to be actually the bronze spear.

c974bd1645c508b38da07ebe4e33e5635b95f781

**Comment by asl97** [comment]
due to: https://github.com/kaadmy/pixture/commit/823261023ac9292cd72ce0648b6ca1129ef671a2#diff-43ece095762ee6ee8594eeea123c17f8R690
