### ISSUE TITLE
Can't sleep in bed

### ISSUE THREAD

**Issue by Wuzzy2** [kaadmy/pixture#60]
It seems I can't sleep in my bed. I tried rightclicking, jumping, punching, shift+rightclick, etc.
Nothing works, neither at day or night.

c974bd1645c508b38da07ebe4e33e5635b95f781

**Comment by kaadmy** [comment]
Hm, is this with a new bed or an existing one?
By"can't sleep" what do you mean? Can't get in the bed? Can't "sleep" at night?

**Comment by Wuzzy2** [comment]
Well, is it even possible to sleep in the bed or is it just a decorational item? Or how am I supposed to use the bed?

As I said, nothing happens on rightclick, jumping, punchng, etc.

**Comment by kaadmy** [comment]
The bed should be usable, it works correctly it I do
- `/giveme bed:bed`
- Place it
- Right-click on it to lie down
- Right-click on it again to exit

Lying down at night will set the bed as your new spawnpoint when you die/

**Comment by Wuzzy2** [comment]
Hmm, okay. It works in new world but not in my old one, even after re-placing the bed.
Is there a workaround for me (e.g. must I delete/edit files)?

**Comment by kaadmy** [comment]
If you were in a bed when you entered it it might've had issues since the node meta might have been invalid.
Another possibility is that the bed file is being read incorrectly.

**Comment by Wuzzy2** [comment]
Probably just a legacy thing then.
