### ISSUE TITLE
Birch Logs -> Planks

### ISSUE THREAD

**Issue by Jaen-Minetest** [kaadmy/pixture#69]
Birch logs currently can't be crafted into planks as you can with oak logs. If you ever update this game, please allow all types of logs to be crafted into planks. Thank you.

**Comment by Wuzzy2** [comment]
This is no longer the case, as of e0865f77c15a8dc23293ee0c1c0b36f54905a150.

**Comment by kaadmy** [comment]
Is that the correct commit?

**Comment by Wuzzy2** [comment]
“as of <commit>“ means, “at the time <commit> was part of the repo, this sentence is true”.

So, in the repository, at the time of e0865f7, it is true that you CAN craft birch logs to planks.

I did not search for the actual commit that added the change …

By the way, this is just the latest commit, as of today.

**Comment by Wuzzy2** [comment]
Gosh, oh GitHub, you little …

I meant to say:

> “as of [INSERT COMMIT HERE]“ means, “at the time [INSERT COMMIT HERE] was part of the repo, this sentence is true”.

**Comment by kaadmy** [comment]
Ah okay, my bad, I misunderstood that.

It seems that as of fdb2e119 Birch logs have had a crafting recipe (and currently works in e0865f7) , unless there's something else wrong as well as this.
